import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.css'


import Footer from '../components/footer/footer'
import LeftSide from '../components/left-side/leftside'
import RightSide from '../components/right-side/rightside'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Mentor - Mult-Step Form Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <LeftSide />
        <RightSide />
      </main>

      <Footer />

    </div >
  )
}
export default Home
